const ProductActionTypes = {
    GET_PRODUCTS: 'get_products',
    GET_PRODUCTS_BY_ARRIVAL: 'get_products_by_arrival',
    GET_PRODUCTS_BY_BRAND: 'get_products_by_brand',
    GET_PRODUCT_DETAIL: 'get_product_detail',
    CLEAR_PRODUCT_DETAIL: 'clear_product_detail',
    GET_RANDOM_PRODUCT: 'get_random_product',
    GET_ALL_PRODUCTS_BY_BRAND: 'get_all_products_by_brand',
    GET_MODELS: 'get_models',
    GET_PRODUCTS_TO_SHOP: 'get_products_to_shop',
    FETCH_ARRIVAL_START: 'FETCH_ARRIVAL_START',
    FETCH_ARRIVAL_SUCCESS: 'FETCH_ARRIVAL_SUCCESS',
    FETCH_ARRIVAL_FAILURE: 'FETCH_ARRIVAL_FAILURE',
    GET_PRODUCTS_START: 'GET_PRODUCTS_START',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
    FETCH_BY_BRAND_START: 'FETCH_BY_BRAND_START',
    FETCH_BY_BRAND_SUCCESS: 'FETCH_BY_BRAND_SUCCSESS',
    FETCH_BY_BRAND_FAILURE: 'FETCH_BY_BRAND_FAILURE',
    GET_PRODUCT_DETAIL_START: 'GET_PRODUCT_DETAIL_START',
    GET_PRODUCT_DETAIL_SUCCESS: 'GET_PRODUCT_DETAIL_SUCCESS',
    GET_PRODUCT_DETAIL_FAILURE: 'GET_PRODUCT_DETAIL_FAILURE',
    CLEAR_PRODUCT_START: 'CLEAR_PRODUCT_START',
    CLEAR_PRODUCT_SUCCESS: 'CLEAR_PRODUCT_SUCCESS',
    CLEAR_PRODUCT_FAILURE: 'CLEAR_PRODUCT_FAILURE',
    GET_RANDOM_PRODUCT_START: 'GET_RANDOM_PRODUCT_START',
    GET_RANDOM_PRODUCT_SUCCESS: 'GET_RANDOM_PRODUCT_SUCCESS',
    GET_RANDOM_PRODUCT_FAILURE: 'GET_RANDOM_PRODUCT_FAILURE',
    GET_ALL_PRODUCTS_BY_BRAND_START: 'GET_ALL_PRODUCTS_BY_BRAND_START',
    GET_ALL_PRODUCTS_BY_BRAND_SUCCESS: 'GET_ALL_RPODUCTS_BY_BRAND_SUCCESS',
    GET_ALL_PRODUCTS_BY_BRAND_FAILURE: 'GET_ALL_PRODUCTS_BY_BRAND_FAILURE',
    GET_FILTER_PRODUCT_START: 'GET_FILTER_PRODUCT_START',
    GET_FILTER_PRODUCT_SUCCESS: 'GET_FILTER_PRODUCT_SUCCESS',
    GET_FILTER_PRODUCT_FAILURE: 'GET_FILTER_PRODUCT_FAILURE',
    GET_MODELS_START: 'GET_MODELS_START',
    GET_MODELS_SUCCESS: 'GET_MODELS_SUCCESS',
    GET_MODELS_FAILURE: 'GET_MODELS_FAILURE',
    GET_BRAND_NAME_START: 'GET_BRAND_NAME_START',
    GET_BRAND_NAME_SUCCESS: 'GET_BRAND_NAME_SUCCESS',
    GET_BRAND_NAME_FAILURE: 'GET_BRAND_NAME_FAILURE'
}

export default ProductActionTypes;
// export const GET_PRODUCTS = 'get_products';
// export const GET_PRODUCTS_BY_ARRIVAL = 'get_products_by_arrival';
// export const GET_PRODUCTS_BY_BRAND = 'get_products_by_brand';
// export const GET_PRODUCT_DETAIL = 'get_product_detail';
// export const CLEAR_PRODUCT_DETAIL = 'clear_product_detail';
// export const GET_RANDOM_PRODUCT = 'get_random_product';
// export const GET_ALL_PRODUCTS_BY_BRAND = 'get_all_products_by_brand';
// export const GET_MODELS = 'get_models';
// export const GET_PRODUCTS_TO_SHOP = 'get_products_to_shop';